// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ZCZokzB1GeJZK1_R8hcP_SGQCoUxk5A',
    appId: '1:378008961204:web:01f3585bacf939be35d7e1',
    messagingSenderId: '378008961204',
    projectId: 'attendance-flutter-app-3d686',
    authDomain: 'attendance-flutter-app-3d686.firebaseapp.com',
    storageBucket: 'attendance-flutter-app-3d686.appspot.com',
    measurementId: 'G-7WESG0830W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApOtHO3Nbnosv5YZzU8p6KQl9PeyIBB2s',
    appId: '1:378008961204:android:7f9811fac9f33d4435d7e1',
    messagingSenderId: '378008961204',
    projectId: 'attendance-flutter-app-3d686',
    storageBucket: 'attendance-flutter-app-3d686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwrVNdxRyGA6cVoLPLBV0XRPYDa2SSTKg',
    appId: '1:378008961204:ios:f752d33f389fc47235d7e1',
    messagingSenderId: '378008961204',
    projectId: 'attendance-flutter-app-3d686',
    storageBucket: 'attendance-flutter-app-3d686.appspot.com',
    iosBundleId: 'com.example.cli',
  );
}
